spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: always
springdoc:
  springdoc:
    api-docs:
      enabled: true
      path: /v3/api-docs/swagger-config
    swagger-ui:
      path: /index.html
      disable-swagger-default-url: true
      config-url: /v3/api-docs/swagger-config
      url: /v3/api-docs