spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId:
            clientSecret:
  sql:
    init:
      mode: always

      #SMTP configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

springdoc:
  springdoc:
    api-docs:
      enabled: true
      path: /v3/api-docs/swagger-config
    swagger-ui:
      path: /index.html
      disable-swagger-default-url: true
      config-url: /v3/api-docs/swagger-config
      url: /v3/api-docs

#secure token configuration
secure:
  token:
    validity: 2
site:
  base:
    url: http://localhost:8080